//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osu_bot.Assets
{
    using System;
    using SkiaSharp;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("osu_bot.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static SKImage AP
        {
            get
            {
                object obj = ResourceManager.GetObject("AP", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage ApprovedStatus
        {
            get
            {
                object obj = ResourceManager.GetObject("ApprovedStatus", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage AT
        {
            get
            {
                object obj = ResourceManager.GetObject("AT", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage DT
        {
            get
            {
                object obj = ResourceManager.GetObject("DT", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage EZ
        {
            get
            {
                object obj = ResourceManager.GetObject("EZ", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage FL
        {
            get
            {
                object obj = ResourceManager.GetObject("FL", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage GraveyardStatus
        {
            get
            {
                object obj = ResourceManager.GetObject("GraveyardStatus", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage HD
        {
            get
            {
                object obj = ResourceManager.GetObject("HD", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage HR
        {
            get
            {
                object obj = ResourceManager.GetObject("HR", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage HT
        {
            get
            {
                object obj = ResourceManager.GetObject("HT", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage LovedStatus
        {
            get
            {
                object obj = ResourceManager.GetObject("LovedStatus", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage NC
        {
            get
            {
                object obj = ResourceManager.GetObject("NC", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage NF
        {
            get
            {
                object obj = ResourceManager.GetObject("NF", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage PF
        {
            get
            {
                object obj = ResourceManager.GetObject("PF", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage RatingStatus
        {
            get
            {
                object obj = ResourceManager.GetObject("RatingStatus", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage RL
        {
            get
            {
                object obj = ResourceManager.GetObject("RL", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage SD
        {
            get
            {
                object obj = ResourceManager.GetObject("SD", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }

        internal static SKImage SO
        {
            get
            {
                object obj = ResourceManager.GetObject("SO", resourceCulture);
                byte[] data = (byte[])obj;
                return SKImage.FromEncodedData(data);
            }
        }
    }
}
